#! / bin / bash
# gausah di recode ya
# kode warna
a = ' \ 033 [1; 31m '
b = ' \ 033 [1; 32m '
c = ' \ 033 [1; 33m '
d = ' \ 033 [1; 34m '
e = ' \ 033 [1; 35m '
f = ' \ 033 [1; 36m '
o = ' \ 033 [0m '
bersih
spanduk () {
echo -e " " " \ 033 [1; 32m
╔══════════════════════════════════════╗
  Welcome To My Tools Wisnu ID
╚══════════════════════════════════════╝
██ ██ ██▄ ▄██ ██ ████████               
██ ▄▄ ██▀█▄█▀██ ▄▄ ██ ╔═╗ ╔═╔═        
██ ██ ██ ▀ ██ ██ ██ ╚═╣╣ ╣╠═╠═╔═╗        
██████ ██ ██ ██ ██ ██ ╚╚═╝╚═╚═╣ ╣
╔══════════════════════════════════════════════╗
 Author : Wisnu | Panjull                                          
 Github : https://github.com/cyberlimit
 YouTube: Wisnu ID
╚══════════════════════════════════════════════╝
" " "
}

cek () {
termux-setup-storage
perintah -v exiftool > / dev / null 2> & 1  || { echo -e > & 2  " $ {b} exiftool belum terinstall silahkan ketik \ n. $ {a} pkg install exiftool -y $ {o} " ;  keluar 1 ; }
perintah -v pv > / dev / null 2> & 1  || { echo -e > & 2  " pv belum terinstall silahkan ketik, \ n $ {a} pkg install pv -y $ {o} " ;  keluar 1 ; }
}


mulai () {
gema
baca -p $ ' \ 033 [1; 33mSilahkan masukan lokasi gambar: \ 033 [1; 32m ' gambar
echo -e " $ {d} Mencoba untuk mengambil informasi ... "  | pv -qL 10
echo -e " $ {e} "
exiftool $ gambar
echo -e " $ {o} Selesai "
read -p $ ' \ 033 [1; 36mMau again ga: \ 033 [1; 33m ' lagi
if [[ $ lagi  ==  " lagi "  ||  $ lagi  ==  " y "  ||  $ lagi  ==  " mau "  ||  $ lagi  ==  " Y "  ||  $ lagi  ==  " ya " ]] ;  kemudian
bersih
tidur 1,5
spanduk
mulai
lain
echo -e " $ {o} "
keluar
fi
}
spanduk
cek
mulai
